# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import langgraph_pb2 as langgraph__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in langgraph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LangGraphServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunGraph = channel.unary_unary(
                '/langgraph.LangGraphService/RunGraph',
                request_serializer=langgraph__pb2.GraphRequest.SerializeToString,
                response_deserializer=langgraph__pb2.GraphResponse.FromString,
                _registered_method=True)
        self.RunGraphStream = channel.unary_stream(
                '/langgraph.LangGraphService/RunGraphStream',
                request_serializer=langgraph__pb2.GraphRequest.SerializeToString,
                response_deserializer=langgraph__pb2.GraphResponse.FromString,
                _registered_method=True)


class LangGraphServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunGraphStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LangGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.RunGraph,
                    request_deserializer=langgraph__pb2.GraphRequest.FromString,
                    response_serializer=langgraph__pb2.GraphResponse.SerializeToString,
            ),
            'RunGraphStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RunGraphStream,
                    request_deserializer=langgraph__pb2.GraphRequest.FromString,
                    response_serializer=langgraph__pb2.GraphResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'langgraph.LangGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('langgraph.LangGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LangGraphService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/langgraph.LangGraphService/RunGraph',
            langgraph__pb2.GraphRequest.SerializeToString,
            langgraph__pb2.GraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunGraphStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/langgraph.LangGraphService/RunGraphStream',
            langgraph__pb2.GraphRequest.SerializeToString,
            langgraph__pb2.GraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
