# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: langgraph.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'langgraph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flanggraph.proto\x12\tlanggraph\"\"\n\x0cGraphRequest\x12\x12\n\nuser_input\x18\x01 \x01(\t\"\x1f\n\rGraphResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x98\x01\n\x10LangGraphService\x12=\n\x08RunGraph\x12\x17.langgraph.GraphRequest\x1a\x18.langgraph.GraphResponse\x12\x45\n\x0eRunGraphStream\x12\x17.langgraph.GraphRequest\x1a\x18.langgraph.GraphResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'langgraph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRAPHREQUEST']._serialized_start=30
  _globals['_GRAPHREQUEST']._serialized_end=64
  _globals['_GRAPHRESPONSE']._serialized_start=66
  _globals['_GRAPHRESPONSE']._serialized_end=97
  _globals['_LANGGRAPHSERVICE']._serialized_start=100
  _globals['_LANGGRAPHSERVICE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
