name: Build Complete Windows Installer

on:
  push:
    paths:
      - grpc-desktop-app/**
      - .github/workflows/**

jobs:
  build-electron:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node dependencies
        run: |
          cd grpc-desktop-app
          npm install

      - name: Download and install Miniconda
        run: |
          Invoke-WebRequest https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -OutFile miniconda.exe
          Start-Process .\miniconda.exe -Wait -ArgumentList "/InstallationType=JustMe", "/AddToPath=0", "/RegisterPython=0", "/S", "/D=$env:USERPROFILE\miniconda3"

      - name: Create portable Python 3.11 env with pip
        run: |
          $env:Path = "$env:USERPROFILE\miniconda3;$env:USERPROFILE\miniconda3\Scripts;$env:Path"
          $python = "$env:USERPROFILE\miniconda3\python.exe"
          & $python -m conda create --prefix grpc-desktop-app/runtimes/win32/python python=3.11 pip --yes --copy

      - name: Install Python gRPC packages into bundled env
        run: |
          $env:Path = "grpc-desktop-app\runtimes\win32\python;grpc-desktop-app\runtimes\win32\python\Scripts;$env:Path"
          .\grpc-desktop-app\runtimes\win32\python\python.exe -m pip install grpcio grpcio-tools

      - name: Build frontend
        run: |
          cd grpc-desktop-app
          npm run build-frontend

      - name: Build Windows installer
        run: |
          cd grpc-desktop-app
          npm run build

      - name: Upload final installer
        uses: actions/upload-artifact@v4
        with:
          name: Windows Installer
          path: grpc-desktop-app/dist/*.exe
